[package]
name = "intentos_contracts"
version = "0.0.0"

[dependencies]
MinitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "minitia_stdlib", rev = "main" }

[addresses]
std = "0x1"
intentos = "_"

